package config

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/Martin-Winfred/unbound-tui/internal/domain"
)

// Layout of the fragment file (the tool owns it and rewrites it whole):
//
//	# Generated by unbound-tui - do not edit
//
//	local-zone: "example.com." transparent
//	local-data: "web.example.com. 3600 IN A 192.168.1.1"
//
//	# unbound-tui:disabled
//	# local-zone: "old.example." static
//	# local-data: "host.old.example. 300 IN A 192.0.2.9"
//
// Active lines appear bare; disabled entries are kept as commented lines
// after the disabled marker, so a zone can be turned off without losing its
// data. Commented local-zone/local-data lines anywhere in the file count as
// disabled, because the tool is the only writer.
const (
	fragmentHeader = "# Generated by unbound-tui - do not edit"
	disabledMarker = "# unbound-tui:disabled"
)

// SerializeFragment renders the full fragment file. Active entries come
// first (all local-zone lines, then all local-data lines); disabled entries
// follow the marker as commented lines. Records of a disabled zone are
// always written in the disabled block, so a disabled zone never leaks as an
// implicit transparent zone.
func SerializeFragment(zones []domain.Zone) []byte {
	sorted := make([]domain.Zone, len(zones))
	copy(sorted, zones)
	sort.SliceStable(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	var b strings.Builder
	b.WriteString(fragmentHeader + "\n")
	b.WriteString(fmt.Sprintf("# Last updated: %s\n\n", time.Now().UTC().Format(time.RFC3339)))
	// Declare the section explicitly: `include:` inlines the file textually,
	// so local-zone/local-data are only valid inside a server section
	// regardless of where the including config places the include.
	b.WriteString("server:\n")

	for _, z := range sorted {
		if z.Disabled {
			continue
		}
		fmt.Fprintf(&b, "local-zone: %q %s\n", domain.FQDN(z.Name), z.Type)
	}
	for _, z := range sorted {
		if z.Disabled {
			continue
		}
		for _, r := range z.Records {
			if r.Disabled {
				continue
			}
			fmt.Fprintf(&b, "local-data: %q\n", domain.RRString(z.Name, r))
		}
	}

	var disabled []string
	for _, z := range sorted {
		if z.Disabled {
			disabled = append(disabled, fmt.Sprintf("local-zone: %q %s", domain.FQDN(z.Name), z.Type))
		}
	}
	for _, z := range sorted {
		for _, r := range z.Records {
			if z.Disabled || r.Disabled {
				disabled = append(disabled, fmt.Sprintf("local-data: %q", domain.RRString(z.Name, r)))
			}
		}
	}
	if len(disabled) > 0 {
		b.WriteString("\n" + disabledMarker + "\n")
		for _, line := range disabled {
			b.WriteString("# " + line + "\n")
		}
	}
	return []byte(b.String())
}
