package config

import (
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/Martin-Winfred/unbound-tui/internal/domain"
)

// Layout of the fragment file (the tool owns it and rewrites it whole):
//
//	# Generated by unbound-tui - do not edit
//
//	local-zone: "example.com." transparent
//	local-data: "web.example.com. 3600 IN A 192.168.1.1"
//
//	# unbound-tui:disabled
//	# local-zone: "old.example." static
//	# local-data: "host.old.example. 300 IN A 192.0.2.9"
//
// Active lines appear bare; disabled entries are kept as commented lines
// after the disabled marker, so a zone can be turned off without losing its
// data. Commented local-zone/local-data lines anywhere in the file count as
// disabled, because the tool is the only writer.
const (
	fragmentHeader = "# Generated by unbound-tui - do not edit"
	disabledMarker = "# unbound-tui:disabled"
)

// rawZone and rawRecord are the intermediate forms produced by parsing,
// before records are attached to their owning zone.
type rawZone struct {
	name     string
	typ      string
	disabled bool
}

type rawRecord struct {
	owner    string // FQDN with a trailing dot
	ttl      int
	rtype    string
	value    string
	disabled bool
}

// ParseFragment reads the fragment file into zones with their records. A
// missing file yields an empty model and a nil error.
func ParseFragment(path string) ([]domain.Zone, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("read fragment: %w", err)
	}

	var zs []rawZone
	var rs []rawRecord
	for _, line := range strings.Split(string(data), "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			continue
		}
		disabled := false
		if strings.HasPrefix(trimmed, "#") {
			body := strings.TrimSpace(strings.TrimPrefix(trimmed, "#"))
			if !strings.HasPrefix(body, "local-zone:") && !strings.HasPrefix(body, "local-data:") {
				continue // ordinary comment / header
			}
			trimmed = body
			disabled = true
		}
		switch {
		case strings.HasPrefix(trimmed, "local-zone:"):
			z, err := parseZoneLine(trimmed)
			if err != nil {
				return nil, err
			}
			z.disabled = disabled
			zs = append(zs, z)
		case strings.HasPrefix(trimmed, "local-data:"):
			r, err := parseDataLine(trimmed)
			if err != nil {
				return nil, err
			}
			r.disabled = disabled
			rs = append(rs, r)
		}
	}
	return assemble(zs, rs), nil
}

// parseZoneLine parses `local-zone: "<name>" <type>`.
func parseZoneLine(line string) (rawZone, error) {
	rest := strings.TrimSpace(strings.TrimPrefix(line, "local-zone:"))
	name, tail, err := cutToken(rest)
	if err != nil {
		return rawZone{}, fmt.Errorf("local-zone: %w", err)
	}
	typ := strings.TrimSpace(tail)
	if typ == "" {
		typ = "transparent"
	}
	return rawZone{name: domain.FQDN(name), typ: typ}, nil
}

// parseDataLine parses `local-data: "<RR>"`.
func parseDataLine(line string) (rawRecord, error) {
	rest := strings.TrimSpace(strings.TrimPrefix(line, "local-data:"))
	rr, _, err := cutToken(rest)
	if err != nil {
		return rawRecord{}, fmt.Errorf("local-data: %w", err)
	}
	owner, ttl, class, rtype, value, err := parseRR(rr)
	if err != nil {
		return rawRecord{}, fmt.Errorf("local-data %q: %w", rr, err)
	}
	if class != "" && !strings.EqualFold(class, "IN") {
		return rawRecord{}, fmt.Errorf("local-data %q: unsupported class %q", rr, class)
	}
	return rawRecord{owner: domain.FQDN(owner), ttl: ttl, rtype: rtype, value: value}, nil
}

// cutToken returns the first token of s (unquoted when quoted) and the rest.
func cutToken(s string) (token, rest string, err error) {
	s = strings.TrimSpace(s)
	if s == "" {
		return "", "", fmt.Errorf("empty value")
	}
	if s[0] == '"' {
		end := strings.IndexByte(s[1:], '"')
		if end < 0 {
			return "", "", fmt.Errorf("unterminated quote")
		}
		return s[1 : 1+end], strings.TrimSpace(s[2+end:]), nil
	}
	fields := strings.Fields(s)
	return fields[0], strings.TrimSpace(s[len(fields[0]):]), nil
}

// parseRR parses one zonefile RR: `owner [ttl] [class] type rdata`.
func parseRR(line string) (owner string, ttl int, class, rtype, value string, err error) {
	fields := strings.Fields(line)
	if len(fields) < 3 {
		return "", 0, "", "", "", fmt.Errorf("too few fields")
	}
	owner = fields[0]
	rest := fields[1:]
	ttl = 3600
	switch {
	case len(rest) >= 2 && strings.EqualFold(rest[1], "IN"):
		// owner ttl IN type rdata
		if t, e := strconv.Atoi(rest[0]); e == nil {
			ttl = t
		}
		class = rest[1]
		rest = rest[2:]
	case strings.EqualFold(rest[0], "IN"):
		// owner IN [ttl] type rdata
		class = rest[0]
		rest = rest[1:]
		if len(rest) >= 2 {
			if t, e := strconv.Atoi(rest[0]); e == nil {
				ttl = t
				rest = rest[1:]
			}
		}
	default:
		// owner [ttl] type rdata
		if t, e := strconv.Atoi(rest[0]); e == nil {
			ttl = t
			rest = rest[1:]
		}
	}
	if len(rest) < 2 {
		return "", 0, "", "", "", fmt.Errorf("too few fields after class/ttl")
	}
	return owner, ttl, class, strings.ToUpper(rest[0]), strings.Join(rest[1:], " "), nil
}

// assemble attaches records to their innermost owning zone and returns the
// sorted model. Records whose owner matches no declared zone spring an
// implicit transparent zone of that owner (mirroring Unbound's behavior for
// a bare local-data line).
func assemble(zs []rawZone, rs []rawRecord) []domain.Zone {
	byName := make(map[string]*domain.Zone)
	var order []string
	addZone := func(name, typ string, disabled bool) *domain.Zone {
		z, ok := byName[name]
		if !ok {
			z = &domain.Zone{Name: name, Type: typ, Disabled: disabled}
			byName[name] = z
			order = append(order, name)
		}
		return z
	}
	for _, z := range zs {
		if z.name == "" {
			continue
		}
		zone := addZone(z.name, z.typ, z.disabled)
		zone.Type = z.typ
		zone.Disabled = z.disabled
	}

	for _, r := range rs {
		name := owningZoneName(r.owner, order)
		if name == "" {
			name = r.owner
			addZone(name, "transparent", r.disabled)
		}
		zone := byName[name]
		rel := r.owner
		if r.owner == zone.Name {
			rel = "@"
		} else {
			rel = strings.TrimSuffix(r.owner, "."+zone.Name)
		}
		zone.Records = append(zone.Records, domain.Record{
			Name: rel, RType: r.rtype, Value: r.value, TTL: r.ttl, Disabled: r.disabled,
		})
	}

	out := make([]domain.Zone, 0, len(order))
	for _, name := range order {
		z := byName[name]
		sort.SliceStable(z.Records, func(i, j int) bool {
			a, b := z.Records[i], z.Records[j]
			if a.Name != b.Name {
				return a.Name < b.Name
			}
			if a.RType != b.RType {
				return a.RType < b.RType
			}
			return a.Value < b.Value
		})
		out = append(out, *z)
	}
	sort.SliceStable(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// owningZoneName returns the longest declared zone that contains owner, or "".
func owningZoneName(owner string, zoneNames []string) string {
	best := ""
	for _, z := range zoneNames {
		if owner == z || strings.HasSuffix(owner, "."+z) {
			if len(z) > len(best) {
				best = z
			}
		}
	}
	return best
}

// SerializeFragment renders the full fragment file. Active entries come
// first (all local-zone lines, then all local-data lines); disabled entries
// follow the marker as commented lines. Records of a disabled zone are
// always written in the disabled block, so a disabled zone never leaks as an
// implicit transparent zone.
func SerializeFragment(zones []domain.Zone) []byte {
	sorted := make([]domain.Zone, len(zones))
	copy(sorted, zones)
	sort.SliceStable(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	var b strings.Builder
	b.WriteString(fragmentHeader + "\n")
	b.WriteString(fmt.Sprintf("# Last updated: %s\n\n", time.Now().UTC().Format(time.RFC3339)))
	// Declare the section explicitly: `include:` inlines the file textually,
	// so local-zone/local-data are only valid inside a server section
	// regardless of where the including config places the include.
	b.WriteString("server:\n")

	for _, z := range sorted {
		if z.Disabled {
			continue
		}
		fmt.Fprintf(&b, "local-zone: %q %s\n", domain.FQDN(z.Name), z.Type)
	}
	for _, z := range sorted {
		if z.Disabled {
			continue
		}
		for _, r := range z.Records {
			if r.Disabled {
				continue
			}
			fmt.Fprintf(&b, "local-data: %q\n", domain.RRString(z.Name, r))
		}
	}

	var disabled []string
	for _, z := range sorted {
		if z.Disabled {
			disabled = append(disabled, fmt.Sprintf("local-zone: %q %s", domain.FQDN(z.Name), z.Type))
		}
	}
	for _, z := range sorted {
		for _, r := range z.Records {
			if z.Disabled || r.Disabled {
				disabled = append(disabled, fmt.Sprintf("local-data: %q", domain.RRString(z.Name, r)))
			}
		}
	}
	if len(disabled) > 0 {
		b.WriteString("\n" + disabledMarker + "\n")
		for _, line := range disabled {
			b.WriteString("# " + line + "\n")
		}
	}
	return []byte(b.String())
}
