package config

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/Martin-Winfred/unbound-tui/internal/domain"
)

func writeTemp(t *testing.T, content string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "fragment.conf")
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatalf("write temp: %v", err)
	}
	return path
}

func TestParseFragment(t *testing.T) {
	path := writeTemp(t, `# Generated by unbound-tui - do not edit
# Last updated: 2026-09-28T00:00:00Z

local-zone: "example.com." transparent
local-data: "example.com. 300 IN A 192.0.2.1"
local-data: "www.example.com. 300 IN A 192.0.2.2"

# unbound-tui:disabled
# local-zone: "old.example." static
# local-data: "host.old.example. 60 IN A 192.0.2.9"
`)
	f, err := ParseFragment(path)
	if err != nil {
		t.Fatalf("ParseFragment: %v", err)
	}
	got, err := ZonesFromFragment(f)
	if err != nil {
		t.Fatalf("ZonesFromFragment: %v", err)
	}
	want := []domain.Zone{
		{
			Name: "example.com.", Type: "transparent",
			Records: []domain.Record{
				{Name: "@", RType: "A", Value: "192.0.2.1", TTL: 300},
				{Name: "www", RType: "A", Value: "192.0.2.2", TTL: 300},
			},
		},
		{
			Name: "old.example.", Type: "static", Disabled: true,
			Records: []domain.Record{
				{Name: "host", RType: "A", Value: "192.0.2.9", TTL: 60, Disabled: true},
			},
		},
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("ParseFragment =\n%+v\nwant\n%+v", got, want)
	}
}

func TestParseFragmentMissingIsEmpty(t *testing.T) {
	f, err := ParseFragment(filepath.Join(t.TempDir(), "absent.conf"))
	if err != nil {
		t.Fatalf("ParseFragment(absent) = %v, want nil", err)
	}
	got, err := ZonesFromFragment(f)
	if err != nil {
		t.Fatalf("ZonesFromFragment: %v", err)
	}
	if len(got) != 0 {
		t.Errorf("ParseFragment(absent) = %+v, want empty", got)
	}
}

func TestParseFragmentImplicitZone(t *testing.T) {
	path := writeTemp(t, `local-data: "solo.example.com. 300 IN A 192.0.2.1"`)
	f, err := ParseFragment(path)
	if err != nil {
		t.Fatalf("ParseFragment: %v", err)
	}
	got, err := ZonesFromFragment(f)
	if err != nil {
		t.Fatalf("ZonesFromFragment: %v", err)
	}
	want := []domain.Zone{{
		Name: "solo.example.com.", Type: "transparent",
		Records: []domain.Record{{Name: "@", RType: "A", Value: "192.0.2.1", TTL: 300}},
	}}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("ParseFragment = %+v, want %+v", got, want)
	}
}

func TestSerializeFragment(t *testing.T) {
	zones := []domain.Zone{
		{
			Name: "example.com.", Type: "transparent",
			Records: []domain.Record{
				{Name: "@", RType: "A", Value: "192.0.2.1", TTL: 300},
				{Name: "www", RType: "A", Value: "192.0.2.2", TTL: 300},
			},
		},
		{
			Name: "old.example.", Type: "static", Disabled: true,
			Records: []domain.Record{{Name: "host", RType: "A", Value: "192.0.2.9", TTL: 60}},
		},
	}
	out := string(SerializeFragment(zones))
	wantOrder := []string{
		"server:",
		`local-zone: "example.com." transparent`,
		`local-data: "example.com. 300 IN A 192.0.2.1"`,
		`local-data: "www.example.com. 300 IN A 192.0.2.2"`,
		disabledMarker,
		`# local-zone: "old.example." static`,
		`# local-data: "host.old.example. 60 IN A 192.0.2.9"`,
	}
	last := -1
	for _, want := range wantOrder {
		idx := strings.Index(out, want)
		if idx < 0 {
			t.Fatalf("output missing %q\n%s", want, out)
		}
		if idx < last {
			t.Errorf("%q out of order\n%s", want, out)
		}
		last = idx
	}
	// The disabled zone must not appear as an active local-zone line.
	if strings.Contains(out, "\nlocal-zone: \"old.example.\"") {
		t.Errorf("disabled zone emitted as active:\n%s", out)
	}
}

func TestFragmentRoundTrip(t *testing.T) {
	zones := []domain.Zone{
		{
			Name: "a.example.", Type: "transparent",
			Records: []domain.Record{
				{Name: "@", RType: "A", Value: "192.0.2.1", TTL: 300},
				{Name: "www", RType: "A", Value: "192.0.2.2", TTL: 300},
			},
		},
		{
			Name: "b.example.", Type: "static", Disabled: true,
			Records: []domain.Record{{Name: "host", RType: "A", Value: "192.0.2.9", TTL: 60, Disabled: true}},
		},
	}
	path := filepath.Join(t.TempDir(), "round.conf")
	if err := os.WriteFile(path, SerializeFragment(zones), 0644); err != nil {
		t.Fatalf("write: %v", err)
	}
	f, err := ParseFragment(path)
	if err != nil {
		t.Fatalf("ParseFragment: %v", err)
	}
	got, err := ZonesFromFragment(f)
	if err != nil {
		t.Fatalf("ZonesFromFragment: %v", err)
	}
	if !reflect.DeepEqual(got, zones) {
		t.Errorf("round trip =\n%+v\nwant\n%+v", got, zones)
	}
}

func TestParseRR(t *testing.T) {
	tests := []struct {
		line    string
		owner   string
		ttl     int
		class   string
		rtype   string
		value   string
		wantErr bool
	}{
		{line: "web.example.com. 3600 IN A 192.0.2.1", owner: "web.example.com.", ttl: 3600, class: "IN", rtype: "A", value: "192.0.2.1"},
		{line: "web.example.com. IN A 192.0.2.1", owner: "web.example.com.", ttl: 3600, class: "IN", rtype: "A", value: "192.0.2.1"},
		{line: "web.example.com. 300 A 192.0.2.1", owner: "web.example.com.", ttl: 300, rtype: "A", value: "192.0.2.1"},
		{line: "web.example.com. A 192.0.2.1", owner: "web.example.com.", ttl: 3600, rtype: "A", value: "192.0.2.1"},
		{line: "mail.example.com. 60 IN MX 10 mail2.example.com.", owner: "mail.example.com.", ttl: 60, class: "IN", rtype: "MX", value: "10 mail2.example.com."},
		{line: "web.example.com. 300 IN", wantErr: true},
		{line: "only.two", wantErr: true},
	}
	for _, tt := range tests {
		owner, ttl, class, rtype, value, err := parseRR(tt.line)
		if tt.wantErr {
			if err == nil {
				t.Errorf("parseRR(%q) = nil error, want error", tt.line)
			}
			continue
		}
		if err != nil {
			t.Errorf("parseRR(%q) error: %v", tt.line, err)
			continue
		}
		if owner != tt.owner || ttl != tt.ttl || class != tt.class || rtype != tt.rtype || value != tt.value {
			t.Errorf("parseRR(%q) = (%q,%d,%q,%q,%q), want (%q,%d,%q,%q,%q)",
				tt.line, owner, ttl, class, rtype, value, tt.owner, tt.ttl, tt.class, tt.rtype, tt.value)
		}
	}
}

func TestCutToken(t *testing.T) {
	if tok, rest, err := cutToken(`"example.com." transparent`); err != nil || tok != "example.com." || rest != "transparent" {
		t.Errorf(`cutToken quoted = (%q,%q,%v)`, tok, rest, err)
	}
	if tok, _, err := cutToken("bare rest"); err != nil || tok != "bare" {
		t.Errorf("cutToken bare = (%q,%v)", tok, err)
	}
	if _, _, err := cutToken(`"unterminated`); err == nil {
		t.Error("cutToken(unterminated) = nil error, want error")
	}
	if _, _, err := cutToken("   "); err == nil {
		t.Error("cutToken(empty) = nil error, want error")
	}
}
