package config

import (
	"path/filepath"
	"reflect"
	"testing"

	"github.com/Martin-Winfred/unbound-tui/internal/domain"
)

func TestParseFragmentData(t *testing.T) {
	tests := []struct {
		name    string
		src     string
		missing bool // parse a nonexistent path instead of src
		want    domain.Fragment
	}{
		{
			name: "v0.1 golden",
			src: `# Generated by unbound-tui - do not edit
# Last updated: 2026-01-01T00:00:00Z

server:
local-zone: "example.com" refuse
local-data: "example.com. 300 IN A 192.0.2.1"

# unbound-tui:disabled
# local-zone: "old.example" transparent
# local-data: "old.example. 300 IN A 192.0.2.2"
`,
			want: domain.Fragment{Sections: []domain.Section{{
				Kind: "server",
				Entries: []domain.Entry{
					{Key: "local-zone", Value: `"example.com" refuse`},
					{Key: "local-data", Value: `"example.com. 300 IN A 192.0.2.1"`},
					{Key: "local-zone", Value: `"old.example" transparent`, Disabled: true},
					{Key: "local-data", Value: `"old.example. 300 IN A 192.0.2.2"`, Disabled: true},
				},
			}}},
		},
		{
			name: "stray top-level directive",
			src: `include: "/x.conf"
server:
`,
			want: domain.Fragment{Sections: []domain.Section{
				{Kind: "", Entries: []domain.Entry{{Key: "include", Value: `"/x.conf"`}}},
				{Kind: "server"},
			}},
		},
		{
			name: "section-header rule",
			src: `stub-zone:
name: "."
stub-addr: "10.0.0.1"
`,
			want: domain.Fragment{Sections: []domain.Section{{
				Kind: "stub-zone",
				Entries: []domain.Entry{
					{Key: "name", Value: `"."`},
					{Key: "stub-addr", Value: `"10.0.0.1"`},
				},
			}}},
		},
		{
			name: "quoting and repeated keys",
			src: `server:
local-zone: "a.com" transparent
local-zone: "a.com" transparent
`,
			want: domain.Fragment{Sections: []domain.Section{{
				Kind: "server",
				Entries: []domain.Entry{
					{Key: "local-zone", Value: `"a.com" transparent`},
					{Key: "local-zone", Value: `"a.com" transparent`},
				},
			}}},
		},
		{
			name: "new-format disabled block",
			src: `server:
local-zone: "example.com" refuse

# unbound-tui:disabled
# server:
# local-data: "old.example. 300 IN A 192.0.2.2"
# forward-zone:
# name: "."
# forward-addr: 192.0.2.53

# local-data: "x.example. 300 IN A 192.0.2.99"
`,
			want: domain.Fragment{Sections: []domain.Section{
				{
					Kind: "server",
					Entries: []domain.Entry{
						{Key: "local-zone", Value: `"example.com" refuse`},
						{Key: "local-data", Value: `"old.example. 300 IN A 192.0.2.2"`, Disabled: true},
					},
				},
				{
					Kind: "forward-zone",
					Entries: []domain.Entry{
						{Key: "name", Value: `"."`, Disabled: true},
						{Key: "forward-addr", Value: "192.0.2.53", Disabled: true},
					},
				},
			}},
		},
		{
			name: "CRLF",
			src:  "server:\r\nlocal-zone: \"a.com\" refuse\r\n",
			want: domain.Fragment{Sections: []domain.Section{{
				Kind:    "server",
				Entries: []domain.Entry{{Key: "local-zone", Value: `"a.com" refuse`}},
			}}},
		},
		{
			name:    "missing file",
			missing: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if tt.missing {
				got, err := ParseFragment(filepath.Join(t.TempDir(), "absent.conf"))
				if err != nil {
					t.Fatalf("ParseFragment(absent) = %v, want nil", err)
				}
				if len(got.Sections) != 0 {
					t.Fatalf("ParseFragment(absent) = %+v, want empty", got)
				}
				return
			}

			got, err := parseFragment([]byte(tt.src))
			if err != nil {
				t.Fatalf("parseFragment() error: %v", err)
			}
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("parseFragment() =\n%+v\nwant\n%+v", got, tt.want)
			}
		})
	}
}
