package config

import (
	"strings"

	"github.com/Martin-Winfred/unbound-tui/internal/domain"
)

// fragmentHeader is the first line of every generated fragment. The tool owns
// the file and regenerates this header on each write; there is deliberately no
// timestamp, so the output is deterministic.
const fragmentHeader = "# Generated by unbound-tui - do not edit"

// SerializeFragment renders a Fragment as the whole fragment file. It is a
// faithful, deterministic dumper: entries keep their model order and their
// values verbatim, and nothing is sorted, escaped or injected.
//
// Active entries are written as `Key: Value` lines. If any entry is disabled,
// they follow a blank line and the disabledMarker, grouped by section under a
// commented `# Kind:` header (the synthetic top-level section, Kind "", has no
// header) and kept as `# Key: Value` comments.
func SerializeFragment(f domain.Fragment) []byte {
	var b strings.Builder
	// Keep the v0.1 shape: the header line followed by a blank line.
	b.WriteString(fragmentHeader + "\n\n")

	// The synthetic top-level section holds directives that appear before the
	// first section header; it is written first and without a header line.
	for _, s := range f.Sections {
		if s.Kind == "" {
			writeActive(&b, s.Entries)
		}
	}
	// Active entries of every named section, in model order. A section with no
	// active entry is dropped from the active area (a fully-disabled section
	// reappears in the disabled block).
	for _, s := range f.Sections {
		if s.Kind == "" || !hasActive(s.Entries) {
			continue
		}
		b.WriteString(s.Kind + ":\n")
		writeActive(&b, s.Entries)
	}

	if hasAnyDisabled(f.Sections) {
		b.WriteString("\n" + disabledMarker + "\n")
		for _, s := range f.Sections {
			if !hasDisabled(s.Entries) {
				continue
			}
			if s.Kind != "" {
				b.WriteString("# " + s.Kind + ":\n")
			}
			for _, e := range s.Entries {
				if e.Disabled {
					b.WriteString("# " + e.Key + ": " + e.Value + "\n")
				}
			}
		}
	}
	return []byte(b.String())
}

// writeActive emits the enabled entries of a section as `Key: Value` lines.
func writeActive(b *strings.Builder, entries []domain.Entry) {
	for _, e := range entries {
		if e.Disabled {
			continue
		}
		b.WriteString(e.Key + ": " + e.Value + "\n")
	}
}

// hasActive reports whether entries contains at least one enabled entry.
func hasActive(entries []domain.Entry) bool {
	for _, e := range entries {
		if !e.Disabled {
			return true
		}
	}
	return false
}

// hasDisabled reports whether entries contains at least one disabled entry.
func hasDisabled(entries []domain.Entry) bool {
	for _, e := range entries {
		if e.Disabled {
			return true
		}
	}
	return false
}

// hasAnyDisabled reports whether any section holds a disabled entry.
func hasAnyDisabled(sections []domain.Section) bool {
	for _, s := range sections {
		if hasDisabled(s.Entries) {
			return true
		}
	}
	return false
}
