package config

import (
	"bytes"
	"reflect"
	"strings"
	"testing"

	"github.com/Martin-Winfred/unbound-tui/internal/domain"
)

// goldenFragment is the synthetic model pinned by the serializer golden test:
// a top-level include, a server section with an active zone/record and one
// disabled record, and a fully-disabled forward-zone.
func goldenFragment() domain.Fragment {
	return domain.Fragment{Sections: []domain.Section{
		{Kind: "", Entries: []domain.Entry{
			{Key: "include", Value: `"/x.conf"`},
		}},
		{Kind: "server", Entries: []domain.Entry{
			{Key: "local-zone", Value: `"example.com" refuse`},
			{Key: "local-data", Value: `"example.com. 300 IN A 192.0.2.1"`},
			{Key: "local-data", Value: `"old.example. 300 IN A 192.0.2.2"`, Disabled: true},
		}},
		{Kind: "forward-zone", Entries: []domain.Entry{
			{Key: "name", Value: `"."`, Disabled: true},
			{Key: "forward-addr", Value: "192.0.2.53", Disabled: true},
		}},
	}}
}

const goldenFragmentBytes = `# Generated by unbound-tui - do not edit

include: "/x.conf"
server:
local-zone: "example.com" refuse
local-data: "example.com. 300 IN A 192.0.2.1"

# unbound-tui:disabled
# server:
# local-data: "old.example. 300 IN A 192.0.2.2"
# forward-zone:
# name: "."
# forward-addr: 192.0.2.53
`

func TestSerializeFragment(t *testing.T) {
	got := string(SerializeFragment(goldenFragment()))
	if got != goldenFragmentBytes {
		t.Errorf("SerializeFragment =\n%q\nwant\n%q", got, goldenFragmentBytes)
	}
	if strings.Contains(got, "Last updated") {
		t.Errorf("serializer output must not carry a timestamp:\n%s", got)
	}
}

func TestFragmentRoundTrip(t *testing.T) {
	samples := []struct {
		name string
		f    domain.Fragment
	}{
		{name: "golden model", f: goldenFragment()},
		{name: "v0.1 golden", f: frag(t, `# Generated by unbound-tui - do not edit
# Last updated: 2026-01-01T00:00:00Z

server:
local-zone: "example.com" refuse
local-data: "example.com. 300 IN A 192.0.2.1"

# unbound-tui:disabled
# local-zone: "old.example" transparent
# local-data: "old.example. 300 IN A 192.0.2.2"
`)},
		{name: "unknown directives", f: frag(t, `include: "/x.conf"
remote-control:
control-enable: yes
control-interface: "127.0.0.1"
forward-zone:
name: "."
forward-addr: 192.0.2.53
`)},
	}
	for _, tt := range samples {
		t.Run(tt.name, func(t *testing.T) {
			got, err := parseFragment(SerializeFragment(tt.f))
			if err != nil {
				t.Fatalf("parseFragment(SerializeFragment(f)): %v", err)
			}
			if !reflect.DeepEqual(got, tt.f) {
				t.Errorf("round trip =\n%+v\nwant\n%+v", got, tt.f)
			}
		})
	}
}

func TestSerializeDeterministic(t *testing.T) {
	f := goldenFragment()
	if first, second := SerializeFragment(f), SerializeFragment(f); !bytes.Equal(first, second) {
		t.Errorf("SerializeFragment is not deterministic:\n%q\n%q", first, second)
	}
}

func TestSerializeAllDisabled(t *testing.T) {
	f := domain.Fragment{Sections: []domain.Section{
		{Kind: "server", Entries: []domain.Entry{
			{Key: "local-zone", Value: `"example.com" refuse`, Disabled: true},
		}},
		{Kind: "forward-zone", Entries: []domain.Entry{
			{Key: "name", Value: `"."`, Disabled: true},
		}},
	}}

	out := string(SerializeFragment(f))
	for _, line := range strings.Split(out, "\n") {
		if line == "" || line == fragmentHeader || strings.HasPrefix(line, "#") {
			continue
		}
		t.Errorf("all-disabled output has a bare directive line %q\n%s", line, out)
	}
	for _, want := range []string{disabledMarker, "# server:", "# forward-zone:"} {
		if !strings.Contains(out, want) {
			t.Errorf("all-disabled output missing %q\n%s", want, out)
		}
	}

	back, err := parseFragment([]byte(out))
	if err != nil {
		t.Fatalf("parseFragment: %v", err)
	}
	if !reflect.DeepEqual(back, f) {
		t.Errorf("all-disabled round trip =\n%+v\nwant\n%+v", back, f)
	}
}

func TestSerializeEmptyFragment(t *testing.T) {
	out := string(SerializeFragment(domain.Fragment{}))
	want := fragmentHeader + "\n\n"
	if out != want {
		t.Errorf("SerializeFragment(empty) = %q, want %q", out, want)
	}
	if strings.Contains(out, "server:") {
		t.Errorf("empty fragment must not inject a server section: %q", out)
	}
}
